### ISSUE TITLE
Respawn issues (API 8)

### ISSUE THREAD

**Issue by JBYoshi** [SpongePowered/Minecon-2016-Expo#22]
Dropping these here for later reference and fixing.

* When respawning before the boss bar expires, the bar doesn't disappear until the player logs out.
* When respawning after the game ends, you are sent to the spawn point of the round's world, not the lobby.

**Comment by ImMorpheus** [comment]
>  When respawning before the boss bar expires, the bar doesn't disappear until the player logs out.

Fixed by https://github.com/SpongePowered/Royale/commit/1ebe8988b5a9d0fc6e62d0854f335d66208a9a6b

>  When respawning after the game ends, you are sent to the spawn point of the round's world, not the lobby.

Fixed by https://github.com/SpongePowered/Royale/commit/03419a22ebbeb4367bb174cac008985026ec59fd
